version: 1.0
provider:
  name: openfaas
  gateway: https://openfaas-ingress-3rd-uglpec.cloud.okteto.net
functions:
  wordpress:
    lang: python3-flask
    handler: ./wordpress
    image: registry.gitlab.com/uglpec/lpec-fn:wordpress-v1
    limits:
      memory: 100Mi
  prestashop:
    lang: golang-http
    handler: ./prestashop
    image: registry.gitlab.com/uglpec/lpec-fn:prestashop-v1
    limits:
      memory: 100Mi
